territories = {
    # sea:.

    'Adriatic Sea': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'Venice', 'Trieste', 'Albania', 'Ionian Sea', 'Apulia'},
        'units': [],
        'owner': None,
    },
    'Aegean Sea': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'Greece', 'Bulgaria (South Coast)', 'Constantinople', 'Ionian Sea', 'Eastern Mediterranean', 'Smyrna'},
        'units': [],
        'owner': None,
    },
    'Baltic Sea': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'Denmark', 'Kiel', 'Berlin', 'Prussia', 'Gulf of Bothnia', 'Livonia', 'Sweden (South Coast)'},
        'units': [],
        'owner': None,
    },
    'Barents Sea': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'Norway', 'St. Petersburg (North Coast)', 'Norwegian Sea'},
        'units': [],
        'owner': None,
    },
    'Black Sea': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'Bulgaria (East Coast)', 'Rumania', 'Constantinople', 'Ankara', 'Sevastopol', 'Armenia'},
        'units': [],
        'owner': None,
    },
    'Eastern Mediterranean': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'Aegean Sea', 'Smyrna', 'Syria', 'Ionian Sea'},
        'units': [],
        'owner': None,
    },
    'English Channel': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'Mid-Atlantic Ocean', 'Irish Sea', 'Wales', 'London', 'North Sea', 'Belgium', 'Picardy', 'Brest'},
        'units': [],
        'owner': None,
    },
    'Gulf of Bothnia': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'Sweden', 'Finland', 'St. Petersburg (South Coast)', 'Livonia', 'Baltic Sea'},
        'units': [],
        'owner': None,
    },
    'Gulf of Lyon': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'Spain (South Coast)', 'Marseilles', 'Western Mediterranean', 'Tyrrhenian Sea', 'Piedmont', 'Tuscany'},
        'units': [],
        'owner': None,
    },
    'Heligoland Bight': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'North Sea', 'Denmark', 'Kiel', 'Holland'},
        'units': [],
        'owner': None,
    },
    'Ionian Sea': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'Adriatic Sea', 'Albania', 'Greece', 'Aegean Sea', 'Eastern Mediterranean', 'Tyrrhenian Sea', 'Tunisia', 'Naples'},
        'units': [],
        'owner': None,
    },
    'Irish Sea': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'Mid-Atlantic Ocean', 'English Channel', 'Wales', 'Liverpool', 'North Atlantic Ocean'},
        'units': [],
        'owner': None,
    },
    'Mid-Atlantic Ocean': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'North Atlantic Ocean', 'Irish Sea', 'English Channel', 'Brest', 'Gascony', 'Spain (North Coast)', 'Portugal', 'Western Mediterranean', 'North Africa'},
        'units': [],
        'owner': None,
    },
    'North Atlantic Ocean': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'Norwegian Sea', 'North Sea', 'Irish Sea', 'Mid-Atlantic Ocean', 'Liverpool', 'Clyde'},
        'units': [],
        'owner': None,
    },
    'North Sea': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'Norwegian Sea', 'North Atlantic Ocean', 'Irish Sea', 'English Channel', 'Belgium', 'Holland', 'Heligoland Bight', 'Denmark', 'Skagerrak', 'Norway', 'Yorkshire', 'Edinburgh', 'London'},
        'units': [],
        'owner': None,
    },
    'Norwegian Sea': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'North Atlantic Ocean', 'North Sea', 'Norway', 'Barents Sea', 'Clyde', 'Edinburgh'},
        'units': [],
        'owner': None,
    },
    'Skagerrak': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'North Sea', 'Norway', 'Sweden', 'Denmark'},
        'units': [],
        'owner': None,
    },
    'Tyrrhenian Sea': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'Western Mediterranean', 'Gulf of Lyon', 'Tuscany', 'Rome', 'Naples', 'Ionian Sea', 'Tunisia'},
        'units': [],
        'owner': None,
    },
    'Western Mediterranean': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'Spain (South Coast)', 'Mid-Atlantic Ocean', 'Gulf of Lyon', 'Tyrrhenian Sea', 'Tunisia', 'North Africa'},
        'units': [],
        'owner': None,
    },
    #land:
    'Gulf of Bothnia': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'Sweden', 'Finland', 'St. Petersburg (South Coast)', 'Livonia', 'Baltic Sea'},
        'units': [],
        'owner': None,
    },
    'Gulf of Lyon': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'Spain (South Coast)', 'Marseilles', 'Western Mediterranean', 'Tyrrhenian Sea', 'Piedmont', 'Tuscany'},
        'units': [],
        'owner': None,
    },
    'Holland': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'Belgium', 'Ruhr', 'Kiel', 'North Sea', 'Heligoland Bight'},
        'units': [],
        'owner': None,
    },
    'Kiel': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'Denmark', 'Berlin', 'Munich', 'Ruhr', 'Holland', 'Baltic Sea', 'Heligoland Bight'},
        'units': [],
        'owner': None,
    },
    'Liverpool': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'Edinburgh', 'Yorkshire', 'Wales', 'Clyde', 'North Atlantic Ocean', 'Irish Sea'},
        'units': [],
        'owner': None,
    },
    'London': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'Yorkshire', 'Wales', 'English Channel', 'North Sea'},
        'units': [],
        'owner': None,
    },
    'Marseilles': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'Burgundy', 'Gascony', 'Piedmont', 'Spain', 'Gulf of Lyon'},
        'units': [],
        'owner': None,
    },
    'Moscow': {
        'type': 'land',
        'supply_center': True,
        'coastal': False,
        'neighbors': {'St. Petersburg', 'Sevastopol', 'Ukraine', 'Warsaw', 'Livonia'},
        'units': [],
        'owner': None,
    },
    'Munich': {
        'type': 'land',
        'supply_center': True,
        'coastal': False,
        'neighbors': {'Berlin', 'Silesia', 'Bohemia', 'Tyrolia', 'Burgundy', 'Ruhr', 'Kiel'},
        'units': [],
        'owner': None,
    },
    'Naples': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'Rome', 'Apulia', 'Ionian Sea'},
        'units': [],
        'owner': None,
    },
    'Norway': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'St. Petersburg', 'Sweden', 'Finland', 'Barents Sea', 'Norwegian Sea', 'North Sea', 'Skagerrak'},
        'units': [],
        'owner': None,
    },
    'Paris': {
        'type': 'land',
        'supply_center': True,
        'coastal': False,
        'neighbors': {'Brest', 'Picardy', 'Burgundy', 'Gascony'},
        'units': [],
        'owner': None,
    },
    'Portugal': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'Spain', 'Mid-Atlantic Ocean'},
        'units': [],
        'owner': None,
    },
    'Rome': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'Tuscany', 'Venice', 'Apulia', 'Naples', 'Tyrrhenian Sea'},
        'units': [],
        'owner': None,
    },
    'Rumania': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'Ukraine', 'Sevastopol', 'Budapest', 'Serbia', 'Bulgaria', 'Black Sea'},
        'units': [],
        'owner': None,
    },
    'Sevastopol': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'Ukraine', 'Moscow', 'Armenia', 'Black Sea', 'Rumania'},
        'units': [],
        'owner': None,
    },
    'Smyrna': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'Constantinople', 'Ankara', 'Armenia', 'Syria', 'Aegean Sea', 'Eastern Mediterranean'},
        'units': [],
        'owner': None,
    },
    'Spain': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'Portugal', 'Gascony', 'Marseilles', 'Gulf of Lyon', 'Western Mediterranean', 'Mid-Atlantic Ocean'},
        'units': [],
        'owner': None,
    },
    'St. Petersburg': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'Norway', 'Finland', 'Livonia', 'Moscow', 'Barents Sea', 'Gulf of Bothnia'},
        'units': [],
        'owner': None,
    },
    'Sweden': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'Norway', 'Finland', 'Denmark', 'Skagerrak', 'Baltic Sea', 'Gulf of Bothnia'},
        'units': [],
        'owner': None,
    },
    'Trieste': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'Vienna', 'Budapest', 'Serbia', 'Albania', 'Adriatic Sea', 'Venice', 'Tyrolia'},
        'units': [],
        'owner': None,
    },
    'Tunis': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'North Africa', 'Tyrrhenian Sea', 'Western Mediterranean', 'Ionian Sea'},
        'units': [],
        'owner': None,
    },
    'Sweden': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'Norway', 'Finland', 'Denmark', 'Skagerrak', 'Baltic Sea', 'Gulf of Bothnia'},
        'units': [],
        'owner': None,
    },
    'Trieste': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'Vienna', 'Budapest', 'Serbia', 'Albania', 'Adriatic Sea', 'Venice', 'Tyrolia'},
        'units': [],
        'owner': None,
    },
    'Tunis': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'North Africa', 'Tyrrhenian Sea', 'Western Mediterranean', 'Ionian Sea'},
        'units': [],
        'owner': None,
    },
    'Venice': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'Tyrolia', 'Trieste', 'Rome', 'Apulia', 'Adriatic Sea'},
        'units': [],
        'owner': None,
    },
    'Vienna': {
        'type': 'land',
        'supply_center': True,
        'coastal': False,
        'neighbors': {'Tyrolia', 'Trieste', 'Budapest', 'Galicia', 'Bohemia'},
        'units': [],
        'owner': None,
    },
    'Warsaw': {
        'type': 'land',
        'supply_center': True,
        'coastal': False,
        'neighbors': {'Prussia', 'Livonia', 'Moscow', 'Ukraine', 'Galicia', 'Silesia'},
        'units': [],
        'owner': None,
    }
    
}

def get_territories():
    return territories
